version: '3.9'

services:
  main:
    image: redis:6.2-alpine
    container_name: redis-master
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - ./data:/data_cluster
    command: redis-server --port 6380 --appendonly yes
    networks:
      app_subnet:
        ipv4_address: 192.168.0.190

  slave1:
    image: redis:6.2-alpine
    container_name: redis-slave1
    restart: always
    ports:
      - "6381:6381"
    volumes:
      - ./data:/data_cluster
    command: redis-server --slaveof 192.168.0.190 6380 --port 6381 --appendonly yes
    networks:
      app_subnet:
        ipv4_address: 192.168.0.191

  slave2:
    image: redis:6.2-alpine
    container_name: redis-slave2
    restart: always
    ports:
      - "6382:6382"
    volumes:
      - ./data:/data_cluster
    command: redis-server --slaveof 192.168.0.190 6380 --port 6382 --appendonly yes
    networks:
      app_subnet:
        ipv4_address: 192.168.0.192

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24