version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data_redis
    command: redis-server --port 6379 --appendonly yes